set(_CATKIN_CURRENT_PACKAGE "nose_temp")
set(nose_temp_VERSION "0.0.0")
set(nose_temp_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(nose_temp_PACKAGE_FORMAT "2")
set(nose_temp_BUILD_DEPENDS "message_generation" "roscpp" "rospy")
set(nose_temp_BUILD_EXPORT_DEPENDS "message_generation" "roscpp" "rospy")
set(nose_temp_BUILDTOOL_DEPENDS "catkin")
set(nose_temp_BUILDTOOL_EXPORT_DEPENDS )
set(nose_temp_EXEC_DEPENDS "roscpp" "rospy")
set(nose_temp_RUN_DEPENDS "roscpp" "rospy" "message_generation")
set(nose_temp_TEST_DEPENDS )
set(nose_temp_DOC_DEPENDS )
set(nose_temp_URL_WEBSITE "")
set(nose_temp_URL_BUGTRACKER "")
set(nose_temp_URL_REPOSITORY "")
set(nose_temp_DEPRECATED "")