// Generated by gencpp from file muscle_activity/muscle_eg_signal.msg
// DO NOT EDIT!


#ifndef MUSCLE_ACTIVITY_MESSAGE_MUSCLE_EG_SIGNAL_H
#define MUSCLE_ACTIVITY_MESSAGE_MUSCLE_EG_SIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace muscle_activity
{
template <class ContainerAllocator>
struct muscle_eg_signal_
{
  typedef muscle_eg_signal_<ContainerAllocator> Type;

  muscle_eg_signal_()
    : header()
    , name()
    , eg_signal()  {
    }
  muscle_eg_signal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , eg_signal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _eg_signal_type;
  _eg_signal_type eg_signal;





  typedef boost::shared_ptr< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> const> ConstPtr;

}; // struct muscle_eg_signal_

typedef ::muscle_activity::muscle_eg_signal_<std::allocator<void> > muscle_eg_signal;

typedef boost::shared_ptr< ::muscle_activity::muscle_eg_signal > muscle_eg_signalPtr;
typedef boost::shared_ptr< ::muscle_activity::muscle_eg_signal const> muscle_eg_signalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::muscle_activity::muscle_eg_signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace muscle_activity

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'muscle_activity': ['/home/vicon/human_metric/src/muscle_activity/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ecdb2d26a43893b3259d731510454fb";
  }

  static const char* value(const ::muscle_activity::muscle_eg_signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ecdb2d26a43893bULL;
  static const uint64_t static_value2 = 0x3259d731510454fbULL;
};

template<class ContainerAllocator>
struct DataType< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "muscle_activity/muscle_eg_signal";
  }

  static const char* value(const ::muscle_activity::muscle_eg_signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message hold data that describes the Electromyography signal\n\
#\n\
# this messages conatines an arry based on the defined \"name\" sensors (arm, forearm, back, thigh, calf,ect)\n\
#\n\
#\n\
#\n\
#\n\
\n\
Header header\n\
string[] name\n\
float32[] eg_signal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::muscle_activity::muscle_eg_signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.eg_signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct muscle_eg_signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::muscle_activity::muscle_eg_signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::muscle_activity::muscle_eg_signal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "eg_signal[]" << std::endl;
    for (size_t i = 0; i < v.eg_signal.size(); ++i)
    {
      s << indent << "  eg_signal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.eg_signal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSCLE_ACTIVITY_MESSAGE_MUSCLE_EG_SIGNAL_H
