set(_CATKIN_CURRENT_PACKAGE "muscle_activity")
set(muscle_activity_VERSION "0.0.0")
set(muscle_activity_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(muscle_activity_PACKAGE_FORMAT "2")
set(muscle_activity_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(muscle_activity_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(muscle_activity_BUILDTOOL_DEPENDS "catkin")
set(muscle_activity_BUILDTOOL_EXPORT_DEPENDS )
set(muscle_activity_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(muscle_activity_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(muscle_activity_TEST_DEPENDS )
set(muscle_activity_DOC_DEPENDS )
set(muscle_activity_URL_WEBSITE "")
set(muscle_activity_URL_BUGTRACKER "")
set(muscle_activity_URL_REPOSITORY "")
set(muscle_activity_DEPRECATED "")