// Generated by gencpp from file nose_temp/nose_temp.msg
// DO NOT EDIT!


#ifndef NOSE_TEMP_MESSAGE_NOSE_TEMP_H
#define NOSE_TEMP_MESSAGE_NOSE_TEMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nose_temp
{
template <class ContainerAllocator>
struct nose_temp_
{
  typedef nose_temp_<ContainerAllocator> Type;

  nose_temp_()
    : header()
    , temprature(0.0)
    , variance(0.0)  {
    }
  nose_temp_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temprature(0.0)
    , variance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _temprature_type;
  _temprature_type temprature;

   typedef double _variance_type;
  _variance_type variance;





  typedef boost::shared_ptr< ::nose_temp::nose_temp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nose_temp::nose_temp_<ContainerAllocator> const> ConstPtr;

}; // struct nose_temp_

typedef ::nose_temp::nose_temp_<std::allocator<void> > nose_temp;

typedef boost::shared_ptr< ::nose_temp::nose_temp > nose_tempPtr;
typedef boost::shared_ptr< ::nose_temp::nose_temp const> nose_tempConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nose_temp::nose_temp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nose_temp::nose_temp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nose_temp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'nose_temp': ['/home/vicon/human_metric/src/nose_temp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nose_temp::nose_temp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nose_temp::nose_temp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nose_temp::nose_temp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nose_temp::nose_temp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nose_temp::nose_temp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nose_temp::nose_temp_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nose_temp::nose_temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c425f1f093219ce6fd8452e59aff77b";
  }

  static const char* value(const ::nose_temp::nose_temp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c425f1f093219ceULL;
  static const uint64_t static_value2 = 0x6fd8452e59aff77bULL;
};

template<class ContainerAllocator>
struct DataType< ::nose_temp::nose_temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nose_temp/nose_temp";
  }

  static const char* value(const ::nose_temp::nose_temp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nose_temp::nose_temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message hold data that describes the temperature  of the nose signal\n\
#\n\
# this messages conatines an arry based on the defined \"name\" sensors (arm, forearm, back, thigh, calf,ect)\n\
#\n\
#\n\
#\n\
#\n\
\n\
Header header\n\
float64 temprature\n\
float64 variance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::nose_temp::nose_temp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nose_temp::nose_temp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temprature);
      stream.next(m.variance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nose_temp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nose_temp::nose_temp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nose_temp::nose_temp_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temprature: ";
    Printer<double>::stream(s, indent + "  ", v.temprature);
    s << indent << "variance: ";
    Printer<double>::stream(s, indent + "  ", v.variance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOSE_TEMP_MESSAGE_NOSE_TEMP_H
