set(_CATKIN_CURRENT_PACKAGE "muse_signal")
set(muse_signal_VERSION "0.0.0")
set(muse_signal_MAINTAINER "ubuntu <ubuntu@todo.todo>")
set(muse_signal_PACKAGE_FORMAT "2")
set(muse_signal_BUILD_DEPENDS "message_generation" "roscpp" "rospy")
set(muse_signal_BUILD_EXPORT_DEPENDS "message_generation" "roscpp" "rospy")
set(muse_signal_BUILDTOOL_DEPENDS "catkin")
set(muse_signal_BUILDTOOL_EXPORT_DEPENDS )
set(muse_signal_EXEC_DEPENDS "roscpp" "rospy")
set(muse_signal_RUN_DEPENDS "roscpp" "rospy" "message_generation")
set(muse_signal_TEST_DEPENDS )
set(muse_signal_DOC_DEPENDS )
set(muse_signal_URL_WEBSITE "")
set(muse_signal_URL_BUGTRACKER "")
set(muse_signal_URL_REPOSITORY "")
set(muse_signal_DEPRECATED "")