set(_CATKIN_CURRENT_PACKAGE "message_synch")
set(message_synch_VERSION "0.0.0")
set(message_synch_MAINTAINER "vicon <vicon@todo.todo>")
set(message_synch_PACKAGE_FORMAT "2")
set(message_synch_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "muscle_activity")
set(message_synch_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(message_synch_BUILDTOOL_DEPENDS "catkin")
set(message_synch_BUILDTOOL_EXPORT_DEPENDS )
set(message_synch_EXEC_DEPENDS "muscle_activity" "roscpp" "rospy" "std_msgs")
set(message_synch_RUN_DEPENDS "muscle_activity" "roscpp" "rospy" "std_msgs")
set(message_synch_TEST_DEPENDS )
set(message_synch_DOC_DEPENDS )
set(message_synch_URL_WEBSITE "")
set(message_synch_URL_BUGTRACKER "")
set(message_synch_URL_REPOSITORY "")
set(message_synch_DEPRECATED "")