// Generated by gencpp from file utility_pkg/get_time.msg
// DO NOT EDIT!


#ifndef UTILITY_PKG_MESSAGE_GET_TIME_H
#define UTILITY_PKG_MESSAGE_GET_TIME_H

#include <ros/service_traits.h>


#include <utility_pkg/get_timeRequest.h>
#include <utility_pkg/get_timeResponse.h>


namespace utility_pkg
{

struct get_time
{

typedef get_timeRequest Request;
typedef get_timeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_time
} // namespace utility_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utility_pkg::get_time > {
  static const char* value()
  {
    return "d4463b49bd5bb77dbd8c4356f5dc1c28";
  }

  static const char* value(const ::utility_pkg::get_time&) { return value(); }
};

template<>
struct DataType< ::utility_pkg::get_time > {
  static const char* value()
  {
    return "utility_pkg/get_time";
  }

  static const char* value(const ::utility_pkg::get_time&) { return value(); }
};


// service_traits::MD5Sum< ::utility_pkg::get_timeRequest> should match 
// service_traits::MD5Sum< ::utility_pkg::get_time > 
template<>
struct MD5Sum< ::utility_pkg::get_timeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utility_pkg::get_time >::value();
  }
  static const char* value(const ::utility_pkg::get_timeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utility_pkg::get_timeRequest> should match 
// service_traits::DataType< ::utility_pkg::get_time > 
template<>
struct DataType< ::utility_pkg::get_timeRequest>
{
  static const char* value()
  {
    return DataType< ::utility_pkg::get_time >::value();
  }
  static const char* value(const ::utility_pkg::get_timeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utility_pkg::get_timeResponse> should match 
// service_traits::MD5Sum< ::utility_pkg::get_time > 
template<>
struct MD5Sum< ::utility_pkg::get_timeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utility_pkg::get_time >::value();
  }
  static const char* value(const ::utility_pkg::get_timeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utility_pkg::get_timeResponse> should match 
// service_traits::DataType< ::utility_pkg::get_time > 
template<>
struct DataType< ::utility_pkg::get_timeResponse>
{
  static const char* value()
  {
    return DataType< ::utility_pkg::get_time >::value();
  }
  static const char* value(const ::utility_pkg::get_timeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILITY_PKG_MESSAGE_GET_TIME_H
